# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlhanoufAlghayhab_Exam_IOSQuiz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlhanoufAlghayhab_Exam_IOSQuiz

  target 'AlhanoufAlghayhab_Exam_IOSQuizTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlhanoufAlghayhab_Exam_IOSQuizUITests' do
    # Pods for testing
pod 'IQKeyboardManagerSwift'
  end

end
