# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlhanoufAlghayhab_GetFilms' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlhanoufAlghayhab_GetFilms
pod 'Firebase/Analytics'
  target 'AlhanoufAlghayhab_GetFilmsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlhanoufAlghayhab_GetFilmsUITests' do
    # Pods for testing
  end

end
